import pygame

# Custom variables go here

# Input types
KEYBOARD = 0
MOUSE = 1
JOYSTICK = 2

# 
CLICKED = 0
PRESSED = 1
RELEASE = 2

# Keyboard input index
KEY_A_CLICKED = [pygame.K_a,KEYBOARD,CLICKED]
KEY_A_PRESSED = [pygame.K_a,KEYBOARD,PRESSED]
KEY_A_RELEASE = [pygame.K_a,KEYBOARD,RELEASE]
KEY_B_CLICKED = [pygame.K_b,KEYBOARD,CLICKED]
KEY_B_PRESSED = [pygame.K_b,KEYBOARD,PRESSED]
KEY_B_RELEASE = [pygame.K_b,KEYBOARD,RELEASE]
KEY_C_CLICKED = [pygame.K_c,KEYBOARD,CLICKED]
KEY_C_PRESSED = [pygame.K_c,KEYBOARD,PRESSED]
KEY_C_RELEASE = [pygame.K_c,KEYBOARD,RELEASE]
KEY_D_CLICKED = [pygame.K_d,KEYBOARD,CLICKED]
KEY_D_PRESSED = [pygame.K_d,KEYBOARD,PRESSED]
KEY_D_RELEASE = [pygame.K_d,KEYBOARD,RELEASE]
KEY_E_CLICKED = [pygame.K_e,KEYBOARD,CLICKED]
KEY_E_PRESSED = [pygame.K_e,KEYBOARD,PRESSED]
KEY_E_RELEASE = [pygame.K_e,KEYBOARD,RELEASE]
KEY_F_CLICKED = [pygame.K_f,KEYBOARD,CLICKED]
KEY_F_PRESSED = [pygame.K_f,KEYBOARD,PRESSED]
KEY_F_RELEASE = [pygame.K_f,KEYBOARD,RELEASE]
KEY_G_CLICKED = [pygame.K_g,KEYBOARD,CLICKED]
KEY_G_PRESSED = [pygame.K_g,KEYBOARD,PRESSED]
KEY_G_RELEASE = [pygame.K_g,KEYBOARD,RELEASE]
KEY_H_CLICKED = [pygame.K_h,KEYBOARD,CLICKED]
KEY_H_PRESSED = [pygame.K_h,KEYBOARD,PRESSED]
KEY_H_RELEASE = [pygame.K_h,KEYBOARD,RELEASE]
KEY_I_CLICKED = [pygame.K_i,KEYBOARD,CLICKED]
KEY_I_PRESSED = [pygame.K_i,KEYBOARD,PRESSED]
KEY_I_RELEASE = [pygame.K_i,KEYBOARD,RELEASE]
KEY_J_CLICKED = [pygame.K_j,KEYBOARD,CLICKED]
KEY_J_PRESSED = [pygame.K_j,KEYBOARD,PRESSED]
KEY_J_RELEASE = [pygame.K_j,KEYBOARD,RELEASE]
KEY_K_CLICKED = [pygame.K_k,KEYBOARD,CLICKED]
KEY_K_PRESSED = [pygame.K_k,KEYBOARD,PRESSED]
KEY_K_RELEASE = [pygame.K_k,KEYBOARD,RELEASE]
KEY_L_CLICKED = [pygame.K_l,KEYBOARD,CLICKED]
KEY_L_PRESSED = [pygame.K_l,KEYBOARD,PRESSED]
KEY_L_RELEASE = [pygame.K_l,KEYBOARD,RELEASE]
KEY_M_CLICKED = [pygame.K_m,KEYBOARD,CLICKED]
KEY_M_PRESSED = [pygame.K_m,KEYBOARD,PRESSED]
KEY_M_RELEASE = [pygame.K_m,KEYBOARD,RELEASE]
KEY_N_CLICKED = [pygame.K_n,KEYBOARD,CLICKED]
KEY_N_PRESSED = [pygame.K_n,KEYBOARD,PRESSED]
KEY_N_RELEASE = [pygame.K_n,KEYBOARD,RELEASE]
KEY_O_CLICKED = [pygame.K_o,KEYBOARD,CLICKED]
KEY_O_PRESSED = [pygame.K_o,KEYBOARD,PRESSED]
KEY_O_RELEASE = [pygame.K_o,KEYBOARD,RELEASE]
KEY_P_CLICKED = [pygame.K_p,KEYBOARD,CLICKED]
KEY_P_PRESSED = [pygame.K_p,KEYBOARD,PRESSED]
KEY_P_RELEASE = [pygame.K_p,KEYBOARD,RELEASE]
KEY_Q_CLICKED = [pygame.K_q,KEYBOARD,CLICKED]
KEY_Q_PRESSED = [pygame.K_q,KEYBOARD,PRESSED]
KEY_Q_RELEASE = [pygame.K_q,KEYBOARD,RELEASE]
KEY_R_CLICKED = [pygame.K_r,KEYBOARD,CLICKED]
KEY_R_PRESSED = [pygame.K_r,KEYBOARD,PRESSED]
KEY_R_RELEASE = [pygame.K_r,KEYBOARD,RELEASE]
KEY_S_CLICKED = [pygame.K_s,KEYBOARD,CLICKED]
KEY_S_PRESSED = [pygame.K_s,KEYBOARD,PRESSED]
KEY_S_RELEASE = [pygame.K_s,KEYBOARD,RELEASE]
KEY_T_CLICKED = [pygame.K_t,KEYBOARD,CLICKED]
KEY_T_PRESSED = [pygame.K_t,KEYBOARD,PRESSED]
KEY_T_RELEASE = [pygame.K_t,KEYBOARD,RELEASE]
KEY_U_CLICKED = [pygame.K_u,KEYBOARD,CLICKED]
KEY_U_PRESSED = [pygame.K_u,KEYBOARD,PRESSED]
KEY_U_RELEASE = [pygame.K_u,KEYBOARD,RELEASE]
KEY_V_CLICKED = [pygame.K_v,KEYBOARD,CLICKED]
KEY_V_PRESSED = [pygame.K_v,KEYBOARD,PRESSED]
KEY_V_RELEASE = [pygame.K_v,KEYBOARD,RELEASE]
KEY_W_CLICKED = [pygame.K_w,KEYBOARD,CLICKED]
KEY_W_PRESSED = [pygame.K_w,KEYBOARD,PRESSED]
KEY_W_RELEASE = [pygame.K_w,KEYBOARD,RELEASE]
KEY_X_CLICKED = [pygame.K_x,KEYBOARD,CLICKED]
KEY_X_PRESSED = [pygame.K_x,KEYBOARD,PRESSED]
KEY_X_RELEASE = [pygame.K_x,KEYBOARD,RELEASE]
KEY_Y_CLICKED = [pygame.K_y,KEYBOARD,CLICKED]
KEY_Y_PRESSED = [pygame.K_y,KEYBOARD,PRESSED]
KEY_Y_RELEASE = [pygame.K_y,KEYBOARD,RELEASE]
KEY_Z_CLICKED = [pygame.K_z,KEYBOARD,CLICKED]
KEY_Z_PRESSED = [pygame.K_z,KEYBOARD,PRESSED]
KEY_Z_RELEASE = [pygame.K_z,KEYBOARD,RELEASE]
KEY_1_CLICKED = [pygame.K_1,KEYBOARD,CLICKED]
KEY_1_PRESSED = [pygame.K_1,KEYBOARD,PRESSED]
KEY_1_RELEASE = [pygame.K_1,KEYBOARD,RELEASE]
KEY_2_CLICKED = [pygame.K_2,KEYBOARD,CLICKED]
KEY_2_PRESSED = [pygame.K_2,KEYBOARD,PRESSED]
KEY_2_RELEASE = [pygame.K_2,KEYBOARD,RELEASE]
KEY_3_CLICKED = [pygame.K_3,KEYBOARD,CLICKED]
KEY_3_PRESSED = [pygame.K_3,KEYBOARD,PRESSED]
KEY_3_RELEASE = [pygame.K_3,KEYBOARD,RELEASE]
KEY_4_CLICKED = [pygame.K_4,KEYBOARD,CLICKED]
KEY_4_PRESSED = [pygame.K_4,KEYBOARD,PRESSED]
KEY_4_RELEASE = [pygame.K_4,KEYBOARD,RELEASE]
KEY_5_CLICKED = [pygame.K_5,KEYBOARD,CLICKED]
KEY_5_PRESSED = [pygame.K_5,KEYBOARD,PRESSED]
KEY_5_RELEASE = [pygame.K_5,KEYBOARD,RELEASE]
KEY_6_CLICKED = [pygame.K_6,KEYBOARD,CLICKED]
KEY_6_PRESSED = [pygame.K_6,KEYBOARD,PRESSED]
KEY_6_RELEASE = [pygame.K_6,KEYBOARD,RELEASE]
KEY_7_CLICKED = [pygame.K_7,KEYBOARD,CLICKED]
KEY_7_PRESSED = [pygame.K_7,KEYBOARD,PRESSED]
KEY_7_RELEASE = [pygame.K_7,KEYBOARD,RELEASE]
KEY_8_CLICKED = [pygame.K_8,KEYBOARD,CLICKED]
KEY_8_PRESSED = [pygame.K_8,KEYBOARD,PRESSED]
KEY_8_RELEASE = [pygame.K_8,KEYBOARD,RELEASE]
KEY_9_CLICKED = [pygame.K_9,KEYBOARD,CLICKED]
KEY_9_PRESSED = [pygame.K_9,KEYBOARD,PRESSED]
KEY_9_RELEASE = [pygame.K_9,KEYBOARD,RELEASE]
KEY_0_CLICKED = [pygame.K_0,KEYBOARD,CLICKED]
KEY_0_PRESSED = [pygame.K_0,KEYBOARD,PRESSED]
KEY_0_RELEASE = [pygame.K_0,KEYBOARD,RELEASE]
KEY_F1_CLICKED = [pygame.K_F1,KEYBOARD,CLICKED]
KEY_F1_PRESSED = [pygame.K_F1,KEYBOARD,PRESSED]
KEY_F1_RELEASE = [pygame.K_F1,KEYBOARD,RELEASE]
KEY_F2_CLICKED = [pygame.K_F2,KEYBOARD,CLICKED]
KEY_F2_PRESSED = [pygame.K_F2,KEYBOARD,PRESSED]
KEY_F2_RELEASE = [pygame.K_F2,KEYBOARD,RELEASE]
KEY_F3_CLICKED = [pygame.K_F3,KEYBOARD,CLICKED]
KEY_F3_PRESSED = [pygame.K_F3,KEYBOARD,PRESSED]
KEY_F3_RELEASE = [pygame.K_F3,KEYBOARD,RELEASE]
KEY_F4_CLICKED = [pygame.K_F4,KEYBOARD,CLICKED]
KEY_F4_PRESSED = [pygame.K_F4,KEYBOARD,PRESSED]
KEY_F4_RELEASE = [pygame.K_F4,KEYBOARD,RELEASE]
KEY_F5_CLICKED = [pygame.K_F5,KEYBOARD,CLICKED]
KEY_F5_PRESSED = [pygame.K_F5,KEYBOARD,PRESSED]
KEY_F5_RELEASE = [pygame.K_F5,KEYBOARD,RELEASE]
KEY_F6_CLICKED = [pygame.K_F6,KEYBOARD,CLICKED]
KEY_F6_PRESSED = [pygame.K_F6,KEYBOARD,PRESSED]
KEY_F6_RELEASE = [pygame.K_F6,KEYBOARD,RELEASE]
KEY_F7_CLICKED = [pygame.K_F7,KEYBOARD,CLICKED]
KEY_F7_PRESSED = [pygame.K_F7,KEYBOARD,PRESSED]
KEY_F7_RELEASE = [pygame.K_F7,KEYBOARD,RELEASE]
KEY_F8_CLICKED = [pygame.K_F8,KEYBOARD,CLICKED]
KEY_F8_PRESSED = [pygame.K_F8,KEYBOARD,PRESSED]
KEY_F8_RELEASE = [pygame.K_F8,KEYBOARD,RELEASE]
KEY_F9_CLICKED = [pygame.K_F9,KEYBOARD,CLICKED]
KEY_F9_PRESSED = [pygame.K_F9,KEYBOARD,PRESSED]
KEY_F9_RELEASE = [pygame.K_F9,KEYBOARD,RELEASE]
KEY_F10_CLICKED = [pygame.K_F10,KEYBOARD,CLICKED]
KEY_F10_PRESSED = [pygame.K_F10,KEYBOARD,PRESSED]
KEY_F10_RELEASE = [pygame.K_F10,KEYBOARD,RELEASE]
KEY_F11_CLICKED = [pygame.K_F11,KEYBOARD,CLICKED]
KEY_F11_PRESSED = [pygame.K_F11,KEYBOARD,PRESSED]
KEY_F11_RELEASE = [pygame.K_F11,KEYBOARD,RELEASE]
KEY_F12_CLICKED = [pygame.K_F12,KEYBOARD,CLICKED]
KEY_F12_PRESSED = [pygame.K_F12,KEYBOARD,PRESSED]
KEY_F12_RELEASE = [pygame.K_F12,KEYBOARD,RELEASE]
KEY_ARROW_LEFT_CLICKED = [pygame.K_LEFT,KEYBOARD,CLICKED]
KEY_ARROW_LEFT_PRESSED = [pygame.K_LEFT,KEYBOARD,PRESSED]
KEY_ARROW_LEFT_RELEASE = [pygame.K_LEFT,KEYBOARD,RELEASE]
KEY_ARROW_RIGHT_CLICKED = [pygame.K_RIGHT,KEYBOARD,CLICKED]
KEY_ARROW_RIGHT_PRESSED = [pygame.K_RIGHT,KEYBOARD,PRESSED]
KEY_ARROW_RIGHT_RELEASE = [pygame.K_RIGHT,KEYBOARD,RELEASE]
KEY_ARROW_UP_CLICKED = [pygame.K_UP,KEYBOARD,CLICKED]
KEY_ARROW_UP_PRESSED = [pygame.K_UP,KEYBOARD,PRESSED]
KEY_ARROW_UP_RELEASE = [pygame.K_UP,KEYBOARD,RELEASE]
KEY_ARROW_DOWN_CLICKED = [pygame.K_DOWN,KEYBOARD,CLICKED]
KEY_ARROW_DOWN_PRESSED = [pygame.K_DOWN,KEYBOARD,PRESSED]
KEY_ARROW_DOWN_RELEASE = [pygame.K_DOWN,KEYBOARD,RELEASE]
KEY_RETURN_CLICKED = [pygame.K_RETURN,KEYBOARD,CLICKED]
KEY_RETURN_PRESSED = [pygame.K_RETURN,KEYBOARD,PRESSED]
KEY_RETURN_RELEASE = [pygame.K_RETURN,KEYBOARD,RELEASE]
KEY_SPACE_CLICKED = [pygame.K_SPACE,KEYBOARD,CLICKED]
KEY_SPACE_PRESSED = [pygame.K_SPACE,KEYBOARD,PRESSED]
KEY_SPACE_RELEASE = [pygame.K_SPACE,KEYBOARD,RELEASE]
KEY_ESCAPE_CLICKED = [pygame.K_ESCAPE,KEYBOARD,CLICKED]
KEY_ESCAPE_PRESSED = [pygame.K_ESCAPE,KEYBOARD,PRESSED]
KEY_ESCAPE_RELEASE = [pygame.K_ESCAPE,KEYBOARD,RELEASE]
KEY_BACKSPACE_CLICKED = [pygame.K_BACKSPACE,KEYBOARD,CLICKED]
KEY_BACKSPACE_PRESSED = [pygame.K_BACKSPACE,KEYBOARD,PRESSED]
KEY_BACKSPACE_RELEASE = [pygame.K_BACKSPACE,KEYBOARD,RELEASE]

# Mouse input index
MOUSE_CLICK_LEFT = [0,MOUSE]
MOUSE_CLICK_MIDDLE = [1,MOUSE]
MOUSE_CLICK_RIGHT = [2,MOUSE]
MOUSE_PRESSED_LEFT = [3,MOUSE]
MOUSE_PRESSED_MIDDLE = [4,MOUSE]
MOUSE_PRESSED_RIGHT = [5,MOUSE]
MOUSE_RELEASED_LEFT = [6,MOUSE]
MOUSE_RELEASED_MIDDLE = [7,MOUSE]
MOUSE_RELEASED_RIGHT = [8,MOUSE]

# Joystick input index
JOYSTICK_BUTTON_DOWN_CLICKED = [0,JOYSTICK]
JOYSTICK_BUTTON_DOWN_PRESSED = [1,JOYSTICK]
JOYSTICK_BUTTON_DOWN_RELEASED = [2,JOYSTICK]
JOYSTICK_BUTTON_RIGHT_CLICKED = [3,JOYSTICK]
JOYSTICK_BUTTON_RIGHT_PRESSED = [4,JOYSTICK]
JOYSTICK_BUTTON_RIGHT_RELEASED = [5,JOYSTICK]
JOYSTICK_BUTTON_UP_CLICKED = [6,JOYSTICK]
JOYSTICK_BUTTON_UP_PRESSED = [7,JOYSTICK]
JOYSTICK_BUTTON_UP_RELEASED = [8,JOYSTICK]
JOYSTICK_BUTTON_LEFT_CLICKED = [9,JOYSTICK]
JOYSTICK_BUTTON_LEFT_PRESSED = [10,JOYSTICK]
JOYSTICK_BUTTON_LEFT_RELEASED = [11,JOYSTICK]
JOYSTICK_DPAD_DOWN_CLICKED = [12,JOYSTICK]
JOYSTICK_DPAD_DOWN_PRESSED = [13,JOYSTICK]
JOYSTICK_DPAD_DOWN_RELEASED = [14,JOYSTICK]
JOYSTICK_DPAD_RIGHT_CLICKED = [15,JOYSTICK]
JOYSTICK_DPAD_RIGHT_PRESSED = [16,JOYSTICK]
JOYSTICK_DPAD_RIGHT_RELEASED = [17,JOYSTICK]
JOYSTICK_DPAD_UP_CLICKED = [18,JOYSTICK]
JOYSTICK_DPAD_UP_PRESSED = [19,JOYSTICK]
JOYSTICK_DPAD_UP_RELEASED = [20,JOYSTICK]
JOYSTICK_DPAD_LEFT_CLICKED = [21,JOYSTICK]
JOYSTICK_DPAD_LEFT_PRESSED = [22,JOYSTICK]
JOYSTICK_DPAD_LEFT_RELEASED = [23,JOYSTICK]
JOYSTICK_RIGHT_STICK_VERTICAL = [24,JOYSTICK]
JOYSTICK_RIGHT_STICK_HORIZONTAL = [25,JOYSTICK]
JOYSTICK_RIGHT_STICK_CLICKED = [26,JOYSTICK]
JOYSTICK_RIGHT_STICK_PRESSED = [27,JOYSTICK]
JOYSTICK_RIGHT_STICK_RELEASED = [28,JOYSTICK]
JOYSTICK_LEFT_STICK_VERTICAL = [29,JOYSTICK]
JOYSTICK_LEFT_STICK_HORIZONTAL = [30,JOYSTICK]
JOYSTICK_LEFT_STICK_CLICKED = [31,JOYSTICK]
JOYSTICK_LEFT_STICK_PRESSED = [32,JOYSTICK]
JOYSTICK_LEFT_STICK_RELEASED = [33,JOYSTICK]
JOYSTICK_BUTTON_SPECIAL_1_CLICKED = [34,JOYSTICK]
JOYSTICK_BUTTON_SPECIAL_1_PRESSED = [35,JOYSTICK]
JOYSTICK_BUTTON_SPECIAL_1_RELEASED = [36,JOYSTICK]
JOYSTICK_BUTTON_SPECIAL_2_CLICKED = [37,JOYSTICK]
JOYSTICK_BUTTON_SPECIAL_2_PRESSED = [38,JOYSTICK]
JOYSTICK_BUTTON_SPECIAL_2_RELEASED = [39,JOYSTICK]
JOYSTICK_RIGHT_BUMPER_CLICKED = [40,JOYSTICK]
JOYSTICK_RIGHT_BUMPER_PRESSED = [41,JOYSTICK]
JOYSTICK_RIGHT_BUMPER_RELEASED = [42,JOYSTICK]
JOYSTICK_LEFT_BUMPER_CLICKED = [43,JOYSTICK]
JOYSTICK_LEFT_BUMPER_PRESSED = [44,JOYSTICK]
JOYSTICK_LEFT_BUMPER_RELEASED = [45,JOYSTICK]
JOYSTICK_TRIGGER_R2 = [46,JOYSTICK]
JOYSTICK_TRIGGER_L2 = [47,JOYSTICK]

# Joystick types
XBOX_360_CONTROLLER = 0
PLAYSTATION_4_CONTROLLER = 1
PLAYSTATION_5_CONTROLLER = 2
NINTENDO_SWITCH_PRO_CONTROLLER = 3
NINTENDO_SWITCH_JOYCON_CONTROLLER_L = 4
NINTENDO_SWITCH_JOYCON_CONTROLLER_R = 5
NINTENDO_SWITCH_JOYCON_CONTROLLER_L_R = 6

# Joystick button maps
JOYSTICK_XBOX_360_BUTTON_MAP = [
    
    [JOYSTICK_BUTTON_DOWN_CLICKED,JOYSTICK_BUTTON_DOWN_PRESSED,JOYSTICK_BUTTON_DOWN_RELEASED],                     # A BUTTON
    [JOYSTICK_BUTTON_RIGHT_CLICKED,JOYSTICK_BUTTON_RIGHT_PRESSED,JOYSTICK_BUTTON_RIGHT_RELEASED],                  # B BUTTON
    [JOYSTICK_BUTTON_LEFT_CLICKED,JOYSTICK_BUTTON_LEFT_PRESSED,JOYSTICK_BUTTON_LEFT_RELEASED],                     # X BUTTON
    [JOYSTICK_BUTTON_UP_CLICKED,JOYSTICK_BUTTON_UP_PRESSED,JOYSTICK_BUTTON_UP_RELEASED],                           # Y BUTTON
    [JOYSTICK_LEFT_BUMPER_CLICKED,JOYSTICK_LEFT_BUMPER_PRESSED,JOYSTICK_LEFT_BUMPER_RELEASED],                     # LEFT BUMPER
    [JOYSTICK_RIGHT_BUMPER_CLICKED,JOYSTICK_RIGHT_BUMPER_PRESSED,JOYSTICK_RIGHT_BUMPER_RELEASED],                  # RIGHT BUMPER
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],      # BACK BUTTON 
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],      # START BUTTON
    [JOYSTICK_LEFT_STICK_CLICKED,JOYSTICK_LEFT_STICK_PRESSED,JOYSTICK_LEFT_STICK_RELEASED],                        # LEFT STICK
    [JOYSTICK_RIGHT_STICK_CLICKED,JOYSTICK_RIGHT_STICK_PRESSED,JOYSTICK_RIGHT_STICK_RELEASED],                     # RIGHT STICK
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],      # PS BUTTON
    
]

JOYSTICK_PLAYSTATION_4_BUTTON_MAP = [
    [JOYSTICK_BUTTON_DOWN_CLICKED,JOYSTICK_BUTTON_DOWN_PRESSED,JOYSTICK_BUTTON_DOWN_RELEASED],                      # CROSS BUTTON
    [JOYSTICK_BUTTON_RIGHT_CLICKED,JOYSTICK_BUTTON_RIGHT_PRESSED,JOYSTICK_BUTTON_RIGHT_RELEASED],                   # CIRCLE BUTTON
    [JOYSTICK_BUTTON_UP_CLICKED,JOYSTICK_BUTTON_UP_PRESSED,JOYSTICK_BUTTON_UP_RELEASED],                            # TRIANGLE BUTTON
    [JOYSTICK_BUTTON_LEFT_CLICKED,JOYSTICK_BUTTON_LEFT_PRESSED,JOYSTICK_BUTTON_LEFT_RELEASED],                      # SQUARE BUTTON
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],       # SHARE BUTTON  
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],       # PS BUTTON
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],       # OPTIONS BUTTON
    [JOYSTICK_LEFT_STICK_CLICKED,JOYSTICK_LEFT_STICK_PRESSED,JOYSTICK_LEFT_STICK_RELEASED],                         # LEFT STICK
    [JOYSTICK_RIGHT_STICK_CLICKED,JOYSTICK_RIGHT_STICK_PRESSED,JOYSTICK_RIGHT_STICK_RELEASED],                      # RIGHT STICK
    [JOYSTICK_LEFT_BUMPER_CLICKED,JOYSTICK_LEFT_BUMPER_PRESSED,JOYSTICK_LEFT_BUMPER_RELEASED],                      # LEFT BUMPER
    [JOYSTICK_RIGHT_BUMPER_CLICKED,JOYSTICK_RIGHT_BUMPER_PRESSED,JOYSTICK_RIGHT_BUMPER_RELEASED],                   # RIGHT BUMPER
    [JOYSTICK_DPAD_UP_CLICKED,JOYSTICK_DPAD_UP_PRESSED,JOYSTICK_DPAD_UP_RELEASED],                                  # DPAD UP
    [JOYSTICK_DPAD_DOWN_CLICKED,JOYSTICK_DPAD_DOWN_PRESSED,JOYSTICK_DPAD_DOWN_RELEASED],                            # DPAD DOWN
    [JOYSTICK_DPAD_LEFT_CLICKED,JOYSTICK_DPAD_LEFT_PRESSED,JOYSTICK_DPAD_LEFT_RELEASED],                            # DPAD LEFT
    [JOYSTICK_DPAD_RIGHT_CLICKED,JOYSTICK_DPAD_RIGHT_PRESSED,JOYSTICK_DPAD_RIGHT_RELEASED],                         # DPAD RIGHT
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],       # TOUCH PAD
]

JOYSTICK_PLAYSTATION_5_BUTTON_MAP = [
    [JOYSTICK_BUTTON_DOWN_CLICKED,JOYSTICK_BUTTON_DOWN_PRESSED,JOYSTICK_BUTTON_DOWN_RELEASED],                      # CROSS BUTTON
    [JOYSTICK_BUTTON_RIGHT_CLICKED,JOYSTICK_BUTTON_RIGHT_PRESSED,JOYSTICK_BUTTON_RIGHT_RELEASED],                   # CIRCLE BUTTON
    [JOYSTICK_BUTTON_UP_CLICKED,JOYSTICK_BUTTON_UP_PRESSED,JOYSTICK_BUTTON_UP_RELEASED],                            # TRIANGLE BUTTON
    [JOYSTICK_BUTTON_LEFT_CLICKED,JOYSTICK_BUTTON_LEFT_PRESSED,JOYSTICK_BUTTON_LEFT_RELEASED],                      # SQUARE BUTTON
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],       # SHARE BUTTON  
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],       # PS BUTTON
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],       # OPTIONS BUTTON
    [JOYSTICK_LEFT_STICK_CLICKED,JOYSTICK_LEFT_STICK_PRESSED,JOYSTICK_LEFT_STICK_RELEASED],                         # LEFT STICK
    [JOYSTICK_RIGHT_STICK_CLICKED,JOYSTICK_RIGHT_STICK_PRESSED,JOYSTICK_RIGHT_STICK_RELEASED],                      # RIGHT STICK
    [JOYSTICK_LEFT_BUMPER_CLICKED,JOYSTICK_LEFT_BUMPER_PRESSED,JOYSTICK_LEFT_BUMPER_RELEASED],                      # LEFT BUMPER
    [JOYSTICK_RIGHT_BUMPER_CLICKED,JOYSTICK_RIGHT_BUMPER_PRESSED,JOYSTICK_RIGHT_BUMPER_RELEASED],                   # RIGHT BUMPER
    [JOYSTICK_DPAD_UP_CLICKED,JOYSTICK_DPAD_UP_PRESSED,JOYSTICK_DPAD_UP_RELEASED],                                  # DPAD UP
    [JOYSTICK_DPAD_DOWN_CLICKED,JOYSTICK_DPAD_DOWN_PRESSED,JOYSTICK_DPAD_DOWN_RELEASED],                            # DPAD DOWN
    [JOYSTICK_DPAD_LEFT_CLICKED,JOYSTICK_DPAD_LEFT_PRESSED,JOYSTICK_DPAD_LEFT_RELEASED],                            # DPAD LEFT
    [JOYSTICK_DPAD_RIGHT_CLICKED,JOYSTICK_DPAD_RIGHT_PRESSED,JOYSTICK_DPAD_RIGHT_RELEASED],                         # DPAD RIGHT
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],       # TOUCH PAD
]

JOYSTICK_NINTENDO_SWITCH_PRO_CONTROLLER_BUTTON_MAP = [
    [JOYSTICK_BUTTON_RIGHT_CLICKED,JOYSTICK_BUTTON_RIGHT_PRESSED,JOYSTICK_BUTTON_RIGHT_RELEASED],                   # A BUTTON
    [JOYSTICK_BUTTON_DOWN_CLICKED,JOYSTICK_BUTTON_DOWN_PRESSED,JOYSTICK_BUTTON_DOWN_RELEASED],                      # B BUTTON
    [JOYSTICK_BUTTON_UP_CLICKED,JOYSTICK_BUTTON_UP_PRESSED,JOYSTICK_BUTTON_UP_RELEASED],                            # X BUTTON
    [JOYSTICK_BUTTON_LEFT_CLICKED,JOYSTICK_BUTTON_LEFT_PRESSED,JOYSTICK_BUTTON_LEFT_RELEASED],                      # Y BUTTON
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],       # - BUTTON  
    [JOYSTICK_BUTTON_SPECIAL_1_CLICKED,JOYSTICK_BUTTON_SPECIAL_1_PRESSED,JOYSTICK_BUTTON_SPECIAL_1_RELEASED],       # HOME BUTTON
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],       # + BUTTON
    [JOYSTICK_LEFT_STICK_CLICKED,JOYSTICK_LEFT_STICK_PRESSED,JOYSTICK_LEFT_STICK_RELEASED],                         # LEFT STICK
    [JOYSTICK_RIGHT_STICK_CLICKED,JOYSTICK_RIGHT_STICK_PRESSED,JOYSTICK_RIGHT_STICK_RELEASED],                      # RIGHT STICK
    [JOYSTICK_LEFT_BUMPER_CLICKED,JOYSTICK_LEFT_BUMPER_PRESSED,JOYSTICK_LEFT_BUMPER_RELEASED],                      # LEFT BUMPER
    [JOYSTICK_RIGHT_BUMPER_CLICKED,JOYSTICK_RIGHT_BUMPER_PRESSED,JOYSTICK_RIGHT_BUMPER_RELEASED],                   # RIGHT BUMPER
    [JOYSTICK_DPAD_UP_CLICKED,JOYSTICK_DPAD_UP_PRESSED,JOYSTICK_DPAD_UP_RELEASED],                                  # DPAD UP
    [JOYSTICK_DPAD_DOWN_CLICKED,JOYSTICK_DPAD_DOWN_PRESSED,JOYSTICK_DPAD_DOWN_RELEASED],                            # DPAD DOWN
    [JOYSTICK_DPAD_LEFT_CLICKED,JOYSTICK_DPAD_LEFT_PRESSED,JOYSTICK_DPAD_LEFT_RELEASED],                            # DPAD LEFT
    [JOYSTICK_DPAD_RIGHT_CLICKED,JOYSTICK_DPAD_RIGHT_PRESSED,JOYSTICK_DPAD_RIGHT_RELEASED],                         # DPAD RIGHT
    [JOYSTICK_BUTTON_SPECIAL_2_CLICKED,JOYSTICK_BUTTON_SPECIAL_2_PRESSED,JOYSTICK_BUTTON_SPECIAL_2_RELEASED],       # CAPTURE BUTTON
]

JOYSTICK_BUTTON_MAP = [
    JOYSTICK_XBOX_360_BUTTON_MAP,
    JOYSTICK_PLAYSTATION_4_BUTTON_MAP,
    JOYSTICK_PLAYSTATION_5_BUTTON_MAP,
    JOYSTICK_NINTENDO_SWITCH_PRO_CONTROLLER_BUTTON_MAP
]

# Joystick axis map
JOYSTICK_XBOX_360_AXIS_MAP = [
    JOYSTICK_LEFT_STICK_HORIZONTAL,
    JOYSTICK_LEFT_STICK_VERTICAL,
    JOYSTICK_TRIGGER_L2,
    JOYSTICK_RIGHT_STICK_HORIZONTAL,
    JOYSTICK_RIGHT_STICK_VERTICAL,
    JOYSTICK_TRIGGER_R2,
]

JOYSTICK_PLAYSTATION_4_AXIS_MAP= [
    JOYSTICK_LEFT_STICK_HORIZONTAL,
    JOYSTICK_LEFT_STICK_VERTICAL,
    JOYSTICK_RIGHT_STICK_HORIZONTAL,
    JOYSTICK_RIGHT_STICK_VERTICAL,
    JOYSTICK_TRIGGER_L2,
    JOYSTICK_TRIGGER_R2,
]

JOYSTICK_PLAYSTATION_5_AXIS_MAP= [
    JOYSTICK_LEFT_STICK_HORIZONTAL,
    JOYSTICK_LEFT_STICK_VERTICAL,
    JOYSTICK_RIGHT_STICK_HORIZONTAL,
    JOYSTICK_RIGHT_STICK_VERTICAL,
    JOYSTICK_TRIGGER_L2,
    JOYSTICK_TRIGGER_R2,
]

JOYSTICK_NINTENDO_SWITCH_PRO_CONTROLLER_AXIS_MAP= [
    JOYSTICK_LEFT_STICK_HORIZONTAL,
    JOYSTICK_LEFT_STICK_VERTICAL,
    JOYSTICK_RIGHT_STICK_HORIZONTAL,
    JOYSTICK_RIGHT_STICK_VERTICAL,
    JOYSTICK_TRIGGER_L2,
    JOYSTICK_TRIGGER_R2,
]

JOYSTICK_AXIS_MAP = [
    JOYSTICK_XBOX_360_AXIS_MAP,
    JOYSTICK_PLAYSTATION_4_AXIS_MAP,
    JOYSTICK_PLAYSTATION_5_AXIS_MAP,
    JOYSTICK_NINTENDO_SWITCH_PRO_CONTROLLER_AXIS_MAP
]

# Joystick hat map
JOYSTICK_XBOX_360_HAT_MAP = [
    None
]

JOYSTICK_HAT_MAP = [
    JOYSTICK_XBOX_360_HAT_MAP
]

